# Generated by Django 4.0.2 on 2022-05-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
                ('creator', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('published_date', models.CharField(max_length=200)),
                ('reading_time', models.CharField(max_length=200)),
            ],
        ),
    ]
