# Generated by Django 4.0.2 on 2022-05-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='num',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
