# Generated by Django 4.0.2 on 2022-05-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='tag',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
